app.security.jwt.secret=VGhhbmhuYWRtaW5KV1RTZWNyZXRLRXkxMjM0NTY3ODkwMTIzNA==
app.security.jwt.expiration-in-minutes=60
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:tramed}
spring.data.redis.timeout=2s
