version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-testUser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-abcd@1234}
      POSTGRES_DB: ${DB_NAME:-testDb}
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-testDb}
      DB_USER: ${DB_USER:-testUser}
      DB_PASSWORD: ${DB_PASSWORD:-abcd@1234}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-tramed}
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\" --appendonly yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: