spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:testDb}
    username: ${DB_USER:testUser}
    password: ${DB_PASSWORD:abcd@1234}
    driver-class-name: org.postgresql.Driver

security:
  test-user-id: 22222222-2222-2222-2222-222222222222
